spring:
  datasource:
    username: postgres
    password: 1987891
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_control

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
