spring:
  datasource:
    username: macbookpro
    password: 19801980
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test



  cache:
    type: redis
    redis:
      time-to-live: 60s

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true