spring:
  datasource:
    username: postgres
    password: math2606
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_control

  jpa:
    hibernate:
      ddl-auto: create # default none
    show-sql: true

